### ISSUE TITLE
In BeagleBoneBlack it throws an argument error.

### ISSUE THREAD

**Issue by kfatehi** [bitgamma/elixir_serial#4]
Hi.

Thanks for this package I've been using it successfully on my Mac for working with an Arduino.

On the Beaglebone, however, with `/dev/ttyACM0` as the Arduino connected via USB, I get this error and crash when trying to call `Serial.open/2`.

Maybe you have an idea?

Thanks

```
iex(branch@nerves)3> {:ok, serial} = Serial.start_link
{:ok, #PID<0.115.0>}
iex(branch@nerves)4>
nil
iex(branch@nerves)5> Serial.open(serial, "/dev/ttyACM0")
** (EXIT from #PID<0.110.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.port_command(#Port<0.1278>, [3, "/dev/ttyACM0"])
        (serial) lib/serial.ex:99: Serial.handle_call/3
        (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)

00:03:37.171 [error] GenServer #PID<0.115.0> terminating
** (ArgumentError) argument error
    :erlang.port_command(#Port<0.1278>, [3, "/dev/ttyACM0"])
    (serial) lib/serial.ex:99: Serial.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:open, "/dev/ttyACM0"}
State: {#PID<0.110.0>, #Port<0.1278>}

=CRASH REPORT==== 1-Jan-1970::00:03:37 ===
  crasher:
    initial call: Elixir.Serial:init/1
    pid: <0.115.0>
    registered_name: []
    exception exit: {badarg,
                        [{erlang,port_command,
                             [#Port<0.1278>,[3,<<"/dev/ttyACM0">>]],
                             []},
                         {'Elixir.Serial',handle_call,3,
                             [{file,"lib/serial.ex"},{line,99}]},
                         {gen_server,try_handle_call,4,
                             [{file,"gen_server.erl"},{line,629}]},
                         {gen_server,handle_msg,5,
                             [{file,"gen_server.erl"},{line,661}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,240}]}]}
      in function  gen_server:terminate/7 (gen_server.erl, line 826)
    ancestors: [<0.110.0>]
    messages: []
    links: [<0.110.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 141
  neighbours:
    neighbour: [{pid,<0.110.0>},
                  {registered_name,[]},
                  {initial_call,{erlang,apply,2}},
                  {current_function,{gen,do_call,4}},
                  {ancestors,[]},
                  {messages,[]},
                  {links,[<0.115.0>]},
                  {dictionary,
                      [{iex_history,
                           #{'__struct__' => 'Elixir.IEx.History.State',
                             queue => {[{4,"\n",nil},
                               {3,"{:ok, serial} = Serial.start_link\n",
                                {ok,<0.115.0>}},
                               {2,"\n",nil}],
                              [{1,"\n",nil}]},
                             size => 4,
                             start => 1}}]},
                  {trap_exit,false},
                  {status,waiting},
                  {heap_size,4185},
                  {stack_size,50},
                  {reductions,6273}]
iex(branch@nerves)1>
```

**Comment by bitgamma** [comment]
interesting. I use this on an custom ARM board myself (but not using Nerves) with Elixir 1.0.5. I plan installing a Nerves based system on a RasPi soon, and I will try to reproduce. If you can find the error, PR is always welcome
